=== ArtemKazakov/FinalWebProjectHostel_Kazakov/src/main/resources/xsd/bean.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://hostel.com/bean"
            xmlns:bean="http://hostel.com/bean"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified">

    <xsd:element name="beans">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="bean" type="bean:beanType" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="beanType">
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="class" type="xsd:string" use="required"/>
    </xsd:complexType>
</xsd:schema>

=== ArtemKazakov/FinalWebProjectHostel_Kazakov/src/main/resources/bean/daobeans.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://hostel.com/bean"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://hostel.com/bean http://hostel.com/bean.xsd">

    <bean name="passportDAO" class="com.epam.hostel.dao.impl.MySQLPassportDAO"/>

    <bean name="poolDAO" class="com.epam.hostel.dao.impl.MySQLPoolDAO"/>

    <bean name="roomDAO" class="com.epam.hostel.dao.impl.MySQLRoomDAO"/>

    <bean name="userDAO" class="com.epam.hostel.dao.impl.MySQLUserDAO"/>

    <bean name="discountDAO" class="com.epam.hostel.dao.impl.MySQLDiscountDAO"/>

    <bean name="requestDAO" class="com.epam.hostel.dao.impl.MySQLRequestDAO"/>

    <bean name="scheduleRecordDAO" class="com.epam.hostel.dao.impl.MySQLScheduleRecordDAO"/>

</beans>

=== ArtemKazakov/FinalWebProjectHostel_Kazakov/src/main/resources/bean/servicebeans.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://hostel.com/bean"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://hostel.com/bean http://hostel.com/bean.xsd">

    <bean name="siteService" class="com.epam.hostel.service.impl.SiteServiceImpl"/>

    <bean name="poolService" class="com.epam.hostel.service.impl.PoolServiceImpl"/>

    <bean name="roomService" class="com.epam.hostel.service.impl.RoomServiceImpl"/>

    <bean name="userService" class="com.epam.hostel.service.impl.UserServiceImpl"/>

    <bean name="discountService" class="com.epam.hostel.service.impl.DiscountServiceImpl"/>

    <bean name="rentalRequestService" class="com.epam.hostel.service.impl.RentalRequestServiceImpl"/>

    <bean name="scheduleRecordService" class="com.epam.hostel.service.impl.ScheduleRecordServiceImpl"/>

</beans>
