=== ArtemKazakov/FinalWebProjectHostel_Kazakov/src/main/resources/xsd/command.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://hostel.com/command"
            xmlns:cmd="http://hostel.com/command"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified">

    <xsd:element name="commands">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="command" type="cmd:commandType" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="commandType">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="class" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="method" type="cmd:methodType" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="methodType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="POST"/>
            <xsd:enumeration value="GET"/>
            <xsd:enumeration value="OPTIONS"/>
            <xsd:enumeration value="HEAD"/>
            <xsd:enumeration value="PUT"/>
            <xsd:enumeration value="PATCH"/>
            <xsd:enumeration value="DELETE"/>
            <xsd:enumeration value="TRACE"/>
            <xsd:enumeration value="CONNECT"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== ArtemKazakov/FinalWebProjectHostel_Kazakov/src/main/resources/command/commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<commands xmlns="http://hostel.com/command"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://hostel.com/command http://hostel.com/command.xsd">
    <command>
        <name>mainPage</name>
        <class>com.epam.hostel.command.impl.general.ViewMainPageCommand</class>
        <method>GET</method>
    </command>
    <command>
        <name>log_in</name>
        <class>com.epam.hostel.command.impl.general.LogInCommand</class>
        <method>POST</method>
    </command>
    <command>
        <name>log_out</name>
        <class>com.epam.hostel.command.impl.general.LogOutCommand</class>
        <method>POST</method>
    </command>
    <command>
        <name>registration</name>
        <class>com.epam.hostel.command.impl.general.RegistrationCommand</class>
        <method>POST</method>
    </command>
    <command>
        <name>registrationPage</name>
        <class>com.epam.hostel.command.impl.general.RegistrationPageCommand</class>
        <method>GET</method>
    </command>
    <command>
        <name>viewRoomsList</name>
        <class>com.epam.hostel.command.impl.room.ViewRoomsListCommand</class>
        <method>GET</method>
    </command>
    <command>
        <name>error</name>
        <class>com.epam.hostel.command.impl.general.ErrorCommand</class>
        <method>GET</method>
    </command>
    <command>
        <name>serverError</name>
        <class>com.epam.hostel.command.impl.general.ServerErrorCommand</class>
        <method>GET</method>
    </command>
    <command>
        <name>userAccount</name>
        <class>com.epam.hostel.command.impl.user.UserAccountCommand</class>
        <method>GET</method>
    </command>
    <command>
        <name>editUser</name>
        <class>com.epam.hostel.command.impl.user.EditUserCommand</class>
        <method>POST</method>
    </command>
    <command>
        <name>viewUsersList</name>
        <class>com.epam.hostel.command.impl.user.ViewUsersListCommand</class>
        <method>GET</method>
    </command>
    <command>
        <name>viewUser</name>
        <class>com.epam.hostel.command.impl.user.ViewUserCommand</class>
        <method>GET</method>
    </command>
    <command>
        <name>changeLanguage</name>
        <class>com.epam.hostel.command.impl.general.ChangeLanguageCommand</class>
        <method>POST</method>
    </command>
    <command>
        <name>addDiscount</name>
        <class>com.epam.hostel.command.impl.discount.AddDiscountCommand</class>
        <method>POST</method>
    </command>
    <command>
        <name>findSuitableRooms</name>
        <class>com.epam.hostel.command.impl.room.FindSuitableRoomsCommand</class>
        <method>GET</method>
    </command>
    <command>
        <name>makeRentalRequest</name>
        <class>com.epam.hostel.command.impl.rentalrequest.MakeRentalRequestCommand</class>
        <method>POST</method>
    </command>
    <command>
        <name>banUser</name>
        <class>com.epam.hostel.command.impl.user.BanUserCommand</class>
        <method>GET</method>
    </command>
    <command>
        <name>deleteUser</name>
        <class>com.epam.hostel.command.impl.user.DeleteUserCommand</class>
        <method>GET</method>
    </command>
    <command>
        <name>deleteDiscount</name>
        <class>com.epam.hostel.command.impl.discount.DeleteDiscountCommand</class>
        <method>GET</method>
    </command>
    <command>
        <name>editDiscount</name>
        <class>com.epam.hostel.command.impl.discount.EditDiscountCommand</class>
        <method>POST</method>
    </command>
    <command>
        <name>addRoom</name>
        <class>com.epam.hostel.command.impl.room.AddRoomCommand</class>
        <method>POST</method>
    </command>
    <command>
        <name>editRoom</name>
        <class>com.epam.hostel.command.impl.room.EditRoomCommand</class>
        <method>POST</method>
    </command>
    <command>
        <name>deleteRoom</name>
        <class>com.epam.hostel.command.impl.room.DeleteRoomCommand</class>
        <method>GET</method>
    </command>
    <command>
        <name>viewRequestsList</name>
        <class>com.epam.hostel.command.impl.rentalrequest.ViewRentalRequestsListCommand</class>
        <method>GET</method>
    </command>
    <command>
        <name>viewScheduleRecords</name>
        <class>com.epam.hostel.command.impl.schedulerecord.ViewScheduleRecordsListCommand</class>
        <method>GET</method>
    </command>
    <command>
        <name>viewRequest</name>
        <class>com.epam.hostel.command.impl.rentalrequest.ViewRentalRequestCommand</class>
        <method>GET</method>
    </command>
    <command>
        <name>editRequest</name>
        <class>com.epam.hostel.command.impl.rentalrequest.EditRentalRequestCommand</class>
        <method>GET</method>
    </command>
    <command>
        <name>deleteRequest</name>
        <class>com.epam.hostel.command.impl.rentalrequest.DeleteRentalRequestCommand</class>
        <method>GET</method>
    </command>

</commands>
